# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1

# agregar las extensiones aqui
# Ejemplo: RUN elasticsearch-plugin install analysis-icu
